// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProjetoArtCouro.Test.API.Controllers.Usuarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UsuarioController")]
    public partial class UsuarioControllerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UsuarioController.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "UsuarioController", "\tPara funcionalidade cadastro de usuário\r\n\tEu como um usuário do sistema\r\n\tDesejo" +
                    " utilizar os métodos CRUD do usuário.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Tentar cadastrar um usuário sem preencher todos os campos")]
        public virtual void TentarCadastrarUmUsuarioSemPreencherTodosOsCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tentar cadastrar um usuário sem preencher todos os campos", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
#line 7
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table1, "Dado ");
#line 9
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 10
 testRunner.Then("retorne erro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cadastrar um usuário preenchendo todos os campos")]
        public virtual void CadastrarUmUsuarioPreenchendoTodosOsCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar um usuário preenchendo todos os campos", null, ((string[])(null)));
#line 12
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table2.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table2.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
            table2.AddRow(new string[] {
                        "ConfirmarSenha",
                        "!@#Mudar"});
            table2.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table2.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 13
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table2, "Dado ");
#line 20
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 21
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar um usuário sem filtros")]
        public virtual void PesquisarUmUsuarioSemFiltros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar um usuário sem filtros", null, ((string[])(null)));
#line 23
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
#line 24
 testRunner.Given("que preencha os dados do filtro de pesquisa de usuario com as seguintes informaçõ" +
                    "es:", ((string)(null)), table3, "Dado ");
#line 26
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/PesquisarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 27
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar um usuário por nome, situacao e grupo de permissão")]
        public virtual void PesquisarUmUsuarioPorNomeSituacaoEGrupoDePermissao()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar um usuário por nome, situacao e grupo de permissão", null, ((string[])(null)));
#line 29
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table4.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
            table4.AddRow(new string[] {
                        "ConfirmarSenha",
                        "!@#Mudar"});
            table4.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table4.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 30
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table4, "Dado ");
#line 37
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 38
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table5.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table5.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 39
 testRunner.Given("que preencha os dados do filtro de pesquisa de usuario com as seguintes informaçõ" +
                    "es:", ((string)(null)), table5, "Dado ");
#line 44
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/PesquisarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 45
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 46
 testRunner.And("que o retorno tenha uma lista com \'1\' itens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Pesquisar um usuário por código")]
        public virtual void PesquisarUmUsuarioPorCodigo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pesquisar um usuário por código", null, ((string[])(null)));
#line 48
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table6.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
            table6.AddRow(new string[] {
                        "ConfirmarSenha",
                        "!@#Mudar"});
            table6.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table6.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 49
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table6, "Dado ");
#line 56
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 57
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 58
 testRunner.When("realizar uma chamada Get ao endereço \'api/Usuario/PesquisarUsuarioPorCodigo/2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 59
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editar um usuário preenchendo todos os campos")]
        public virtual void EditarUmUsuarioPreenchendoTodosOsCampos()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Editar um usuário preenchendo todos os campos", null, ((string[])(null)));
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table7.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table7.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
            table7.AddRow(new string[] {
                        "ConfirmarSenha",
                        "!@#Mudar"});
            table7.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table7.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 62
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table7, "Dado ");
#line 69
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 70
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "UsuarioCodigo",
                        "2"});
            table8.AddRow(new string[] {
                        "UsuarioNome",
                        "Usuario"});
            table8.AddRow(new string[] {
                        "Senha",
                        "11254!@"});
            table8.AddRow(new string[] {
                        "ConfirmarSenha",
                        "11254!@"});
            table8.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table8.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 71
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table8, "Dado ");
#line 79
 testRunner.When("realizar uma chamada Put ao endereço \'api/Usuario/EditarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 80
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editar senha do usuário logado")]
        public virtual void EditarSenhaDoUsuarioLogado()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Editar senha do usuário logado", null, ((string[])(null)));
#line 82
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table9.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
#line 83
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table9, "Dado ");
#line 86
 testRunner.When("realizar uma chamada Put ao endereço \'api/Usuario/AlterarSenha\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 87
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "Senha",
                        "admin"});
#line 88
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table10, "Dado ");
#line 91
 testRunner.When("realizar uma chamada Put ao endereço \'api/Usuario/AlterarSenha\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 92
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Excluir um usuário por código")]
        public virtual void ExcluirUmUsuarioPorCodigo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Excluir um usuário por código", null, ((string[])(null)));
#line 94
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table11.AddRow(new string[] {
                        "UsuarioNome",
                        "Operador"});
            table11.AddRow(new string[] {
                        "Senha",
                        "!@#Mudar"});
            table11.AddRow(new string[] {
                        "ConfirmarSenha",
                        "!@#Mudar"});
            table11.AddRow(new string[] {
                        "Ativo",
                        "True"});
            table11.AddRow(new string[] {
                        "GrupoCodigo",
                        "1"});
#line 95
 testRunner.Given("que preencha os dados do usuario com as seguintes informações:", ((string)(null)), table11, "Dado ");
#line 102
 testRunner.When("realizar uma chamada Post ao endereço \'api/Usuario/CriarUsuario\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 103
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 104
 testRunner.When("realizar uma chamada Delete ao endereço \'api/Usuario/ExcluirUsuario/2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 105
 testRunner.Then("retorne sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
